name: TrepSupplyCo
favicon: null
layout_spectrum: 0.7641085959039629
typography_spectrum: 0.40153199527412653
title: TrepSupply.co
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.18390943459235132
  lightness: 0.4970276386011392
  saturation: 0.18061904842033982
  rhythmicContrast: 0.5765378603246063
purpose: []
