name: TrepSupplyCo
favicon: null
layout_spectrum: 1
typography_spectrum: 0.40153199527412653
title: TrepSupply.co
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#bf1e2d'
    - '#225e9f'
    - '#698dc6'
    - '#e8785c'
    - '#003366'
  brandStrength: 0.375
  lightness: 0.4970276386011392
  saturation: 0.18061904842033982
  rhythmicContrast: 0.5765378603246063
purpose: []
